---
- name: Create swap file
  hosts: all:!control_plane:!worker_nodes
  become: true
  tasks:
  - name: Check for existing swap file
    ansible.builtin.stat:
      path: /swapfile
    register: swapfile_stat

  - name: Create swap file
    ansible.builtin.command: fallocate -l 4G /swapfile
    when: not swapfile_stat.stat.exists

  - name: Set permissions on swap file
    ansible.builtin.file:
      path: /swapfile
      owner: root
      group: root
      mode: '0600'
    when: not swapfile_stat.stat.exists

  - name: Make swap file
    ansible.builtin.command: mkswap /swapfile
    when: not swapfile_stat.stat.exists

  - name: Enable swap file
    ansible.builtin.command: swapon /swapfile
    when: not swapfile_stat.stat.exists

  - name: Add swap file to fstab
    ansible.builtin.mount:
      name: none
      src: /swapfile
      fstype: swap
      opts: sw
      state: present
    when: not swapfile_stat.stat.exists
