---
- name: Install Helm on Kubernetes Control Plane
  hosts: ubuntu-01
  become: yes
  tasks:

  - name: Download Helm installation script
    get_url:
      url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
      dest: "/tmp/get_helm.sh"
      mode: '0755'

  - name: Install Helm
    command: /tmp/get_helm.sh

  - name: Verify Helm installation
    command: helm version
    register: helm_output
    changed_when: false

  - name: Display Helm version
    debug:
      msg: "{{ helm_output.stdout }}"
