---
- name: Install Docker on all machines
  hosts: all
  become: yes
  roles:
  - geerlingguy.docker

  tasks:
  - name: Add user marwiesing to the docker group
    user:
      name: marwiesing
      groups: docker
      append: yes
