---
- name: Install Kubernetes (K8s) on All Nodes
  hosts: all
  become: yes
  vars:
    kubernetes_version: "1.32"
    kubernetes_role: "worker" # Default role for all nodes

  pre_tasks:
  - name: Load br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: Ensure br_netfilter is enabled at boot
    copy:
      dest: /etc/modules-load.d/k8s.conf
      content: "br_netfilter\n"

  - name: Set Kubernetes sysctl settings
    copy:
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1

  - name: Apply sysctl settings
    command: sysctl --system

  roles:
  - geerlingguy.kubernetes
